/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-data-table-row.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-data-table-row`
 */
declare class EtoolsDataTableRow extends PolymerElement {
  detailsOpened: boolean|null|undefined;
  noCollapse: boolean|null|undefined;
  noAnimation: boolean|null|undefined;
  lowResolutionLayout: boolean|null|undefined;
  mediumResolutionLayout: boolean|null|undefined;
  _toggleRowDetails(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-data-table-row": EtoolsDataTableRow;
  }
}
