/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-data-table-footer.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-data-table-footer`
 */
declare class EtoolsDataTableFooter extends PolymerElement {
  pageSize: string|null|undefined;
  pageSizeOptions: any[]|null|undefined;
  pageNumber: number|null|undefined;
  totalResults: number|null|undefined;
  readonly totalPages: number|null|undefined;
  readonly visibleRange: any[]|null|undefined;
  readonly doNotShow: boolean|null|undefined;
  lowResolutionLayout: boolean|null|undefined;
  _pageLeft(): void;
  _pageRight(): void;
  _firstPage(): void;
  _lastPage(): void;
  _computeTotalPages(pageSize: any, totalResults: any): any;
  _computeVisibleRange(pageNumber: any, pageSize: any, totalResults: any, totalPages: any): any;
  _pageBackDisabled(pageNumber: any): any;
  _pageForwardDisabled(pageNumber: any, totalPages: any): any;
  _hideFooter(totalResults: any): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-data-table-footer": EtoolsDataTableFooter;
  }
}
