/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-data-table-header.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-data-table-header`
 */
declare class EtoolsDataTableHeader extends PolymerElement {
  sortOrder: object|null|undefined;
  _lastSelectedCol: object|null|undefined;
  noTitle: boolean|null|undefined;
  noCollapse: boolean|null|undefined;
  label: string|null|undefined;
  lowResolutionLayout: boolean|null|undefined;
  mediumResolutionLayout: boolean|null|undefined;
  ready(): void;
  _handleSortChanged(e: any): void;
  _sortOrderChanged(sortOrder: any): void;
  _clearSelected(column: any): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-data-table-header": EtoolsDataTableHeader;
  }
}
