/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-data-table-column.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-data-table-column`
 */
declare class EtoolsDataTableColumn extends PolymerElement {
  selected: boolean|null|undefined;
  field: string|null|undefined;
  direction: string|null|undefined;
  ready(): void;
  _sort(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-data-table-column": EtoolsDataTableColumn;
  }
}
